SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


DROP TABLE IF EXISTS hely;
CREATE TABLE hely (
  az int(11) NOT NULL,
  telepules varchar(100) NOT NULL,
  utca varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

DROP TABLE IF EXISTS munkalap;
CREATE TABLE munkalap (
  az int(11) NOT NULL,
  bedatum date NOT NULL,
  javdatum date NOT NULL,
  helyaz int(11) NOT NULL,
  szereloaz int(11) NOT NULL,
  munkaora int(11) NOT NULL,
  anyagar int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

DROP TABLE IF EXISTS szerelo;
CREATE TABLE szerelo (
  az int(11) NOT NULL,
  nev varchar(100) NOT NULL,
  kezdev int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;


ALTER TABLE hely
  ADD PRIMARY KEY (az);

ALTER TABLE munkalap
  ADD PRIMARY KEY (az);

ALTER TABLE szerelo
  ADD PRIMARY KEY (az);


ALTER TABLE hely
  MODIFY az int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE munkalap
  MODIFY az int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE szerelo
  MODIFY az int(11) NOT NULL AUTO_INCREMENT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
